### ISSUE TITLE
Generate reports in the front side

### ISSUE THREAD

**Issue by rpalexis** [GFDRR/sms-lapli#11]
Creating report supports 
          ->Graph (Pie/Plot)
          ->Map
          ->Table
Remember to think about good way to present them

**Comment by rpalexis** [comment]
The base template for the public's reports spache enhanced

**Comment by rpalexis** [comment]
Still need CNSA advice in preparing reports

**Comment by jj0hns0n** [comment]
Once we get some of the sample data into the DB, lets make sure Benjamin
can sit down with Gerry and scope out the kinds of reports he needs.
