### ISSUE TITLE
Put basic data into the system using fixtures

### ISSUE THREAD

**Issue by jbjeanniton** [GFDRR/sms-lapli#18]
Créer un jeu de données valide pour la structure de base du projet

* [x] Department
* [x] Commune
* [x] Section Communale
* [ ] Site Sentinelle
* [x] Type Station Pluviometrique
* [x] Station Pluviometrique

**Comment by jj0hns0n** [comment]
Implemented at 517e57e5a8a4e2e7724f26b39dd5e964db3c69d0

(Site Sentinelle to be handled later)
