### ISSUE TITLE
Receive SMS with the modem

### ISSUE THREAD

**Issue by jbjeanniton** [GFDRR/sms-lapli#2]
We can send SMS with Rapid SMS, Kannel and a GSM modem but we have difficulties to receive the messages.
@Hollyn @alexingfds

**Comment by jj0hns0n** [comment]
Any notes on how to reproduce the problem and the type of modem. Ill test with my setup here if there is an easy way to set it up to test.

**Comment by alexingfds** [comment]
Make sure that kannel is installed . Here you can find our  file configuration (kannel.conf)  and all  to reproduce the problem: https://github.com/GFDRR/Kannel/tree/notReceiveSms

others details :http://djoloftek.blogspot.com/2011/05/configuration-de-kannel.html

**Comment by alexingfds** [comment]
Model:E173s-6
