### ISSUE TITLE
Add a new table "unite" in the data model for units of measurement

### ISSUE THREAD

**Issue by jbjeanniton** [GFDRR/sms-lapli#3]
I think it would be interesting to add a new table to the current data model to facilitate the management of the "_units of measurement_" of the different types of stations through the administration area. 
The different units and their **conversion formulas** will be stored in this table and will allow to easily add new units and new conversions without having to touch the code.

@Esdras1995 @GiovannaB22 @rpalexis

**Comment by Esdras1995** [comment]
that's okay.
