### ISSUE TITLE
Database dump's script content errors relying on python3

### ISSUE THREAD

**Issue by rpalexis** [GFDRR/sms-lapli#36]
Need to know where I can find like
/Users/ortelius/projects/gfdrr-dev/haiti/admin/hti_boundaries_communes_adm2_cnigs_polygon.shp

Cf : load_admin_boundaries.py

**Comment by jj0hns0n** [comment]
These come from haitidata.org

**Comment by jj0hns0n** [comment]
@rpalexis find me in slack and we can discuss. Do you still need these?
